-- 코드를 입력하세요
SELECT 
    MONTH(h.START_DATE) AS MONTH, 
    h.CAR_ID, 
    COUNT(h.CAR_ID) AS RECORDS
FROM 
    (SELECT car_id
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
     GROUP BY car_id
     HAVING COUNT(*) >= 5) AS m 
JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h ON m.CAR_ID = h.CAR_ID
WHERE 
    h.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY 
    MONTH(h.START_DATE), h.CAR_ID
HAVING 
    COUNT(h.CAR_ID) > 0
ORDER BY 
    MONTH(h.START_DATE), h.CAR_ID DESC;