-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(p.price * o.sales_amount) as SALES
FROM PRODUCT as p JOIN OFFLINE_SALE as o ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE