-- 코드를 입력하세요
SELECT b.WRITER_ID, u.NICKNAME, CONCAT(u.CITY, ' ', u.STREET_ADDRESS1, ' ', u.STREET_ADDRESS2) AS 전체주소, 
CONCAT(SUBSTRING(TLNO,1,3), '-', SUBSTRING(TLNO,4,4), '-', SUBSTRING(TLNO,8)) AS 전화번호
FROM USED_GOODS_BOARD AS b JOIN USED_GOODS_USER AS u ON b.WRITER_ID = u.USER_ID
GROUP BY b.WRITER_ID, u.NICKNAME, 전체주소, 전화번호
HAVING COUNT(*) >= 3
ORDER BY b.WRITER_ID DESC;