-- 코드를 입력하세요
SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM ANIMAL_INS AS i JOIN ANIMAL_OUTS AS o ON o.ANIMAL_ID = i.ANIMAL_ID
WHERE i.SEX_UPON_INTAKE REGEXP 'Intact' 
AND (o.SEX_UPON_OUTCOME REGEXP 'Spayed' OR o.SEX_UPON_OUTCOME REGEXP 'Neutered')
ORDER BY i.ANIMAL_ID;