-- 코드를 입력하세요
SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, ROUND(AVG(r.REVIEW_SCORE),2)
FROM REST_INFO AS i, REST_REVIEW AS r
WHERE i.REST_ID = r.REST_ID
GROUP BY i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.ADDRESS
HAVING i.ADDRESS LIKE '서울%'
ORDER BY ROUND(AVG(r.REVIEW_SCORE),2) DESC, i.FAVORITES DESC