-- 코드를 입력하세요
SELECT j.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS t
        FROM JULY
        GROUP BY FLAVOR) AS j JOIN FIRST_HALF AS f ON j.FLAVOR = f.FLAVOR
ORDER BY t + f.TOTAL_ORDER DESC
limit 3