-- 코드를 입력하세요
SELECT j.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS t
        FROM JULY
        GROUP BY FLAVOR) AS j JOIN FIRST_HALF ON j.FLAVOR = FIRST_HALF.FLAVOR
ORDER BY t + FIRST_HALF.TOTAL_ORDER DESC
limit 3