-- 코드를 입력하세요
SELECT p.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE
FROM (SELECT MEMBER_ID, COUNT(*) AS score
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY score DESC
        limit 1) AS s 
        JOIN REST_REVIEW AS r ON s.MEMBER_ID = r.MEMBER_ID
        JOIN MEMBER_PROFILE AS p ON r.MEMBER_ID = p.MEMBER_ID
ORDER BY r.REVIEW_DATE, r.REVIEW_TEXT