-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(p.PRICE * o.AMOUNT)
FROM FOOD_PRODUCT AS p JOIN FOOD_ORDER AS o 
ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE o.PRODUCE_DATE LIKE '2022-05%'
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY SUM(p.PRICE * o.AMOUNT) DESC, p.PRODUCT_ID