-- 코드를 입력하세요
SELECT DATE_FORMAT(DATETIME,'%k') , Count(*) as COUNT
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME,'%k') BETWEEN 9 AND 20
GROUP BY DATE_FORMAT(DATETIME,'%k')
ORDER BY CAST(DATE_FORMAT(DATETIME, '%k') AS SIGNED)