-- 코드를 입력하세요
SELECT DISTINCT c.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS c 
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS r ON c.CAR_ID = r.CAR_ID
WHERE c.CAR_TYPE = '세단' AND r.START_DATE LIKE '%-10-%'
ORDER BY c.CAR_ID DESC;
