-- 코드를 입력하세요
SELECT p.CATEGORY, n.PRICE, p.PRODUCT_NAME
FROM (SELECT CATEGORY , MAX(PRICE) AS PRICE
      FROM FOOD_PRODUCT
      GROUP BY CATEGORY) AS n 
      JOIN FOOD_PRODUCT AS p ON p.PRICE = n.PRICE
WHERE p.CATEGORY IN ('과자','국','김치','식용유')
GROUP BY p.CATEGORY
ORDER BY p.PRICE DESC